# Generated by Django 5.1 on 2024-09-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store_service', '0003_rename_name_store_name_of_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
